# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8c598149a7d1c00fd2fec35e03047b79dbd0e013554174944356a10dbab169da7f968e9a0d5ed1d1804abc3e1395c34b14489faff306e0b522611fb41ea629c

test:
  secret_key_base: 2a136c934095f8425e528cb3469e8429c0e7fdf8aa25e84e7a8a76edf662580e54f1d08a7a0fb782aac68b4a8b35eddb4ad2633909d690aff62cb01e94637d03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
